### PR TITLE
Add a reset method to avoid destroying components

### LINKED ISSUE #7: Reset for path with parameters and children broken
For example, we have two components "app" and "hello" and next path: /app/:projectid/hello .
If we change the path from /app/10/hello to /app/15/hello we will see only "app" component. 
It's happening because you destroy svelte component during reset and we have next algorithm:
destroy hello
render hello
destroy app/:projectid (with nested hello)
render app/:projectid (without nesting hello)

after that, we have only "app" component rendered.
We have two solutions. 
First:
We should destroy hello, destroy app, render app, render hello  (split destroy and render path)
Second:
Just update data params and call cb (activate).

### PR DESCRIPTION
**Pull request by TehShrike**
Fixes #7

Reproduction/test in https://github.com/TehShrike/asr-svelte-renderer-reset-repro

### CODE REVIEW

**Comment by TehShrike** [comment]
I don't think this is a sufficient fix - the state of all state-router-instantiated children need to be reset too.

**Comment by TehShrike** [comment]
Actually, that depends on [this question](https://github.com/TehShrike/abstract-state-router/issues/106#issuecomment-302448862) too

**Comment by TehShrike** [comment]
Yup yup yup, children are reset before parents, so this may actually be sufficient

**Comment by saibotsivad** [comment]
This seems reasonable. 👍

**Comment by TehShrike** [comment]
Published as 1.2.1.

**Pull request merged**
